# Generated by Django 6.0.5 on 2026-06-01 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='planets',
            name='diameter',
            field=models.IntegerField(null=True),
        ),
    ]
