# Generated by Django 6.0.5 on 2026-05-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex03', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='opening_crawl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
